title: Sentinel Hub custom scripts
theme: just-the-docs
description: A repository of custom scripts that can be used with Sentinel-Hub services.
author: Sentinel-Hub by Sinergise
author_email: info@sentinel-hub.com
url: https://custom-scripts.sentinel-hub.com

math: mathjax
enable_copy_code_button: true

logo: "/assets/images/sentinel_hub_logo_with_custom_scripts.png"
favicon_ico: "/assets/images/public_favicon.ico"

permalink: pretty

color_scheme: sentinel_hub

footer_content: 'This work is licensed under a <a target="_blank" rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/"">Creative Commons Attribution-ShareAlike 4.0 International License</a>'

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/sentinel-hub/custom-scripts" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "script"
